###################
# Termux extra keys
###################

extra-keys = [[ \
  {key: 'ESC', popup: {macro: 'cd ~/Workspace ENTER', display: 'ws'}}, \
  '/', \
  '-', \
  'HOME', \
  'UP', \
  {key: 'END', popup: {macro: 'wakelock ENTER', display: 'wake'}}, \
  'PGUP' \
], [ \
  'TAB', \
  'CTRL', \
  'ALT', \
  'LEFT', \
  'DOWN', \
  'RIGHT', \
  'PGDN' \
]]
